[features]
seeds = false
skip-lint = false

[programs.localnet]
case_009 = "LaWkQdqx4dZyNWPTTNwhFx8vsC1koYcdqGizdAtJgK7"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
