[features]
seeds = false
skip-lint = false

[programs.localnet]
case_011 = "8fXbzV1QBWAbe4HYecn6CaLyopkvwSBmshb9T2rLYjjW"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
