[package]
name = 'PriceFetch'
version = '0.0.2'

[addresses]
dexlyn_price_fetcher = "0x34287fd1fae969ae6dca12afb9cd6e95da58aa7a1ddbd19a20138729b2996870"

[dependencies.DexlynClmm]
local = "../DexlynClmm"