[features]
seeds = false
skip-lint = false

[programs.localnet]
case_010 = "FujuvooRjd5dcqKFzffir3KNKhckyonUZijwoYrtUWx3"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
