[features]
seeds = false
skip-lint = false

[programs.localnet]
case_006 = "y2hjj8nStCvwDre7yivavGKgbQhycYp4pbp9BVqAZ4R"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
