[features]
seeds = false
skip-lint = false

[programs.localnet]
case_008 = "APzoQoppD38FonB48EYbqyxpdXrayUaZPSfcb42i6Tbu"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
