[features]
seeds = false
skip-lint = false

[programs.localnet]
case_001 = "k422vULUy4QRmD2BHvrQ2Lr7gcmcRLMPMNRwJVoAHQt"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
