[features]
seeds = false
skip-lint = false

[programs.localnet]
case_015 = "9gw4aWDrWv4vxhefYQC7iATGZrhUxYHC216KqEHp6wM"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
