[features]
seeds = false
skip-lint = false

[programs.localnet]
case_013 = "F7jfkDB7YdsxS6SxqM7NzhysmVmCsAivNCLSNKXEV5vN"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
